M48
; DRILL file {KiCad (6.0.4)} date Mon Aug  1 16:37:02 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-01T16:37:02+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.4)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.5787Y-1.5748
X2.5787Y-3.2283
X7.2441Y-1.5748
X7.2441Y-3.2283
T0
M30
