M48
; DRILL file {KiCad (6.0.7)} date Wed 07 Sep 2022 02:00:28 PM CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-07T14:00:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X0.8658Y-1.2138
X2.5787Y-3.1
X7.2441Y-1.5748
X7.2441Y-3.2283
T0
M30
